import React from 'react'
import Button from './components/Button'
import LogoutButton from './(dashboard)/_(dashboardHeader)/LogoutButton'
import { getCurrentUser } from '@/config/supabase/getCurrentUser'
import MainNavigation from './components/ThisWebsiteOnly/Navigation/MainNavigation'

export const metadata = {
  title: 'Sports Agent Pro',
  // description: 'Generated by create next app',
}

const Homepage = async () => {
  const isLoggedIn = await getCurrentUser()
  console.log('isLoggedIn', isLoggedIn)
  return (
    <>
      <MainNavigation />
      {/* <div className={`${openSans.className}`}> */}
      <p className={''}>Homepage</p>
      <p className={''}>
        {isLoggedIn
          ? `${isLoggedIn?.email} is logged in.`
          : 'You are not logged in'}
      </p>
      {isLoggedIn && <LogoutButton  className={'w-fit'}/>}
      {/* </div> */}
    </>
  )
}

export default Homepage
